function j6h00() {
let x_0=document.getElementById ("d00")
x_0.classList.toggle("model_one")

}
function j6h01() {
    let x_0=document.getElementById ("d01")
    x_0.classList.toggle("model_one")
    
    }
    function j6h02() {
        let x_0=document.getElementById ("d02")
        x_0.classList.toggle("model_one")
        
        }
        function j6h03() {
            let x_0=document.getElementById ("d03")
            x_0.classList.toggle("model_one")
            
            }
            function j6h04() {
                let x_0=document.getElementById ("d04")
                x_0.classList.toggle("model_one")
                
                }
                function j6h05() {
                    let x_0=document.getElementById ("d05")
                    x_0.classList.toggle("model_one")
                    
                    }
                    function j6h06() {
                        let x_0=document.getElementById ("d06")
                        x_0.classList.toggle("model_one")
                        
                        }
                        function j6h07() {
                            let x_0=document.getElementById ("d07")
                            x_0.classList.toggle("model_one")
                            
                            }
                            function j6h08() {
                                let x_0=document.getElementById ("d08")
                                x_0.classList.toggle("model_one")
                                
                                }
                                function j6h09() {
                                    let x_0=document.getElementById ("d09")
                                    x_0.classList.toggle("model_one")
                                    
                                    }
                                    function j6h010() {
                                        let x_0=document.getElementById ("d010")
                                        x_0.classList.toggle("model_one")
                                        
                                        }
                                        function j6h011() {
                                            let x_0=document.getElementById ("d011")
                                            x_0.classList.toggle("model_one")
                                            
                                            }